### ISSUE TITLE
Unexpected behaviours during startup

### ISSUE THREAD

**Issue by NillerMedDild** [Nekeras/borderless#1]
**Description:**
When you set the game to use Borderless Fullscreen and close the game, the window's behaviour during startup is a bit annoying. It cannot be minimized, it takes a long time before it responds, and your screen becomes locked to it. Would it be possible to disable Borderless Fullscreen during startup? :)

**Steps to reproduce:**
1. Start Minecraft, enable Fullscreen
2. Exit Minecraft
3. Start Minecraft

**Versions:**
* Minecraft Version: 1.15.2
* Forge Version: 1.15.2-31.1.63
* Mod Version: borderless-1.15.2-1.0.0

**Comment by NillerMedDild** [comment]
Actually this might be default Minecraft behaviour, my bad ^^' The fullscreen behaviour is exactly the same with the mod as without.

**Comment by Nekeras** [comment]
Yeah, I think this is something related to Minecraft or Forge when a lot of mods are loaded. The window just hangs up and does not respond, even the native fullscreen will crash if you tab out or try to interact with the window.
I will have a look at it anyway and try if there is something I can do to avoid this problem.

**Comment by NillerMedDild** [comment]
The update made the window behaviour more consistent imo, thank you :)
