### ISSUE TITLE
1.19.3, 1.19.4 crash when going to config (in game)

### ISSUE THREAD

**Issue by ForgeTheSteel** [Nekeras/borderless#11]
**Description:**
The game will crash.

**Steps to reproduce:**
1. Start Minecraft
2. Click mods
3. Select Borderless Window
4. Click Config

**Versions:**
* Minecraft Version: 1.19.3, 1.19.4
* Forge Version: 44.12.3 (1.19.3), 45.0.49 (1.19.4)
* Mod Version: BorderlessWindow-1.19.1-1.5.2

**Crash report  (if any, please use [gist](https://gist.github.com/) or [pastebin](https://pastebin.com/) and provide a link here):**
https://gist.github.com/ForgeTheSteel/1de77b03f0deb5174cab2b3080c713a9 (1.19.3)
https://gist.github.com/ForgeTheSteel/273d6a8e7a099bac35b834f26a70470e (1.19.4)

Please list other mods that seem to cause the issue. 
None

**Thank you for your reporting!**

**Comment by Nekeras** [comment]
Thanks for reporting! The crash is resolved for MC 1.19.4.
