### ISSUE TITLE
Server join text collides with "Cancel" button on fullscreen

### ISSUE THREAD

**Issue by SchIaumeyer** [Nekeras/borderless#13]
**Description:**
The text when you join a server is aligned wrong so that you don't see it. Sometimes this makes error messages really hard to read.

**Steps to reproduce:**
1. Start Minecraft
2. Try joining a server
3. The text collides with the "Cancel" button

**Versions:**
* Minecraft Version: 1.20.1 (but exists in all versions)
* Forge Version: 47.2.20
* Mod Version: 1.20-1.6.0

My screen resolution is 2560x1440.

With borders:
![java_BO5TpoeKhV](https://github.com/Nekeras/borderless/assets/51930935/a4641a5c-9c73-4788-a316-52ffd20b4641)

Borderless:
![grafik](https://github.com/Nekeras/borderless/assets/51930935/bebec5bb-b45d-4228-bc72-c54091d08ab2)

**Comment by Nekeras** [comment]
Thanks for reporting!
Is it working correctly in native Minecraft fullscreen mode? Have you tried uninstalling Borderless Window and checked if the text still overlaps the button?

**Comment by SchIaumeyer** [comment]
> Thanks for reporting! Is it working correctly in native Minecraft fullscreen mode? Have you tried uninstalling Borderless Window and checked if the text still overlaps the button?

Oh you're actually right, that seems to be an issue without the mod too

**Comment by Nekeras** [comment]
Yeah, I suspected something like that since this mod only changes some internal window flags and shouldn't affect the window resolution.
Maybe you have another mod that could be causing this behavior. You could also try other GUI scaling settings.
