### ISSUE TITLE
Will not release full screen mode - F11 can lockup game

### ISSUE THREAD

**Issue by ClaudiusMinimus** [Nekeras/borderless#2]
When the game starts I press F11 to switch to full-screen mode, but if I press F11 again nothing happens. It would be nice for the game to switch to a bordered window in case I wanted to tile Minecraft with other apps running.

**Versions:**
* Minecraft Version: 1.15.2
* Forge Version: 31.1.63
* Mod Version: 1.15.2-1.0.1

**Comment by ClaudiusMinimus** [comment]
I just reloaded my client and it was in full-screen mode. I pressed F11 and the game froze. I knew it froze because the roll-over icons did not work. I pressed F11 again and the game was un-froze.

https://paste.ee/p/JjM44

**Comment by Nekeras** [comment]
Does this only happen once Forge says "Freezing data" during the startup? This might be something related to Forge or Minecraft, even the default behavior does freeze the window for some time in the final initialization phase. 
I am also considering a workaround for this problem, I just leave the window in a normal bordered window mode until the initialization is finished and the main menu is opened. With this method, the game freeze might not be that obvious.

**Comment by ClaudiusMinimus** [comment]
Thank you for your reply. I'm sorry to not have gotten back to you sooner. 
The issue is also that once made borderless, I cannot get the borders back unless I disable the mod. F11 does nothing except freeze/un-freeze the buttons.

**Comment by Nekeras** [comment]
Yeah, I just tried it on Ubuntu and some weird behavior is going on. I was only testing this mod on Windows, so I will have a look and try other desktop environments such as KDE Plasma as well. Thanks for reporting.

**Comment by Nekeras** [comment]
I have just published a fix for this issue: 
https://github.com/Nekeras/borderless/releases/tag/1.15.2-1.0.2
The problem should now be fixed with that release. Feel free to reopen this issue in case some further problems arise.

**Comment by ClaudiusMinimus** [comment]
Seems to be fixed. Thanks!
