### ISSUE TITLE
Trying to load any Singleplayer world errors out game

### ISSUE THREAD

**Issue by SeanieGStreams** [Nekeras/borderless#5]
**Description:**
Trying to load into a singleplayer world crashes the game, can join a multiplayer world fine

**Steps to reproduce:**
1. Start Minecraft
2. Load into an existing SP World or create a new singleplayer world
3. ...

**Versions:**
* Minecraft Version: 1.16.5
* Forge Version: 1.16.5-forge36.1.4
* Mod Version: 1.1.0

**Crash report:**
https://pastebin.com/HxYTnMEC

Would really love to see this fixed for Singleplayer so I can use it when I stream minecraft!

**Comment by Nekeras** [comment]
Hey, thanks for reporting. 
The error doesn't seem to be related to my mod. It seems like you are using OptiFine, right? Could you try to use the latest OptiFine version with Forge 1.16.5-36.0.42? OptiFine seems to be very strict with Forge versions. You can download a specific Forge version on the Forge download page ([https://files.minecraftforge.net/](https://files.minecraftforge.net/)) and then clicking on "Show all Versions".

**Comment by SeanieGStreams** [comment]
Hey Nekeras, thanks for the quick reply! 

Tried the suggestions from your reply and sadly got the same result. I'm comparing it to my last crash report and am not sure why it's happening, I'll link the new pastebin so maybe you'll catch something I missed

Pastebin: https://pastebin.com/aMVY0CDb

**Comment by SeanieGStreams** [comment]
Hey Nekeras, thanks for the quick reply!

Trying the versions your recommended still produced the effect, but dowloading both the latest version of Optifine as well as Forge seems to have fixed it! If any other errors arise I'll let you know!

**Comment by Nekeras** [comment]
Great to hear :blush:

Feel free to reopen this issue in case further errors arise.
