### ISSUE TITLE
Screen Event Issue (or at least that's what the error message said)

### ISSUE THREAD

**Issue by Gamemassa** [Nekeras/borderless#8]
**Description:**
I  loaded up Minecraft with several mods, including this Borderless mod, and I got an error message stating that Borderless failed to load correctly and experienced a Screen Event Issue.

**Versions:**
* Minecraft Version: 1.19
* Forge Version: 41.0.85
* Mod Version: 1.5.0

[crash-2022-07-09_15.17.22-fml.txt](https://github.com/Nekeras/borderless/files/9077780/crash-2022-07-09_15.17.22-fml.txt)

**Comment by Nekeras** [comment]
Thanks for reporting! I just tried this with Forge Version 41.0.85. Seems like the Forge team made some internal changes which break the mod. Forge Version 41.0.38 still works fine. I'll have a look and publish a hotfix as soon as possible.

**Comment by Gamemassa** [comment]
Awesome! Thanks so much for the quick reply.

**Comment by Nekeras** [comment]
The crash is resolved with version 1.5.1 for MC 1.19, it should also be backwards compatible with older Forge versions prior to 41.0.64 (https://forums.minecraftforge.net/topic/113541-forge-crash-on-119-with-22-mods/?do=findComment&comment=504718)

**Comment by Gamemassa** [comment]
Yup! It's definitely working now. Thanks again for the rapid response and support.
