### ISSUE TITLE
Error loading Borderless - Sided Setup Event Error

### ISSUE THREAD

**Issue by frogomelette** [Nekeras/borderless#9]
**Description:**
Just an error during loading :( 
"Caused by 0: java.lang.NoClassDefFoundError: net/minecraftforge/client/ConfigGuiHandler$ConfigGuiFactory"

**Steps to reproduce:**
1. Start Minecraft

**Versions:**
* Minecraft Version: 1.19
* Forge Version: 41.0.98
* Mod Version: 1.5.1

**Crash report  (if any, please use [gist](https://gist.github.com/) or [pastebin](https://pastebin.com/) and provide a link here):**
https://pastebin.com/m5mu5V0k

The game loads up fine if I remove borderless, but I absolutely will cry if I can't go to another screen without it minimising D:
Thanks heaps!

**Comment by Nekeras** [comment]
The Forge team made breaking changes, Forge for MC 1.19 is pretty much unstable. For a quick fix, you can downgrade Forge to 41.0.85, this should work (have a look at issue #8).

**Comment by Nekeras** [comment]
Issue is resolved with version 1.5.2. The version is also compatible with MC 1.19.1.
